Scan dev monitor the queue and acquire logs to be scanned
travis-ci/travis-scanner pull request #5
Opened 2022-09-21 12:15 UTC by Jullianos

2022-09-23 09:10 UTC, vitalied requested changes
@Jullianos @AndriiMysko pls rebase

2022-09-23 09:10 UTC, vitalied commented on Gemfile
> +gem 'virtus'
@Jullianos @AndriiMysko `virtus` is discontinued. Use `dry-types`, `dry-struct` and `dry-schema`

2022-09-23 09:10 UTC, vitalied commented on Gemfile
> +gem 'faraday_middleware'
@Jullianos @AndriiMysko `faraday_middleware` is deprecated.
Why you are not using `rest-client` instead of `faraday`?

2022-09-23 10:25 UTC, vitalied commented on lib/travis/remote_log.rb
> +    class Client
@Jullianos @AndriiMysko why are you getting logs via API HTTP calls when you have direct access to the logs DB?

2022-09-27 17:04 UTC, Jullianos commented
@vitalied  This pull-request can be closed as it was replaced by (https://github.com/travis-ci/travis-scanner/pull/7/). Sorry for the inconvenience.

2022-09-27 17:04 UTC, closed without merging